In [186]:
import pandas as pd
import numpy as np

In [187]:
df=pd.read_csv('dirty_dataset.csv')
df

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
0,12369,Hasan D.,200.0,35149,2023-05-30,SALES,Man,America,Sylhet,118.4,0,Good value for money.,219.18,NaN,0
1,7361,Grace P.,NaN,77836,2017-02-27,Engineering,FEMALE,America,Chittagong,71kg,True,Product met all expectations.,329.26,NaN,0
2,3446,Eve D.,20.0,35404,2022-01-18,hr,male,BANGLADESH,Chitagong,98.7,False,Very satisfied with the quality.,438.6,NaN,0
3,18416,Diana E.,47.0,107375,2017-04-15,Marketing,Male,U.K.,Khulna,NaN,false,Delivery was fast and packaging great.,238.03,NaN,0
4,13677,Ira W.,64.0,55962,2021-11-02,SALES,F,United Kingdom,Dhaka,83.5,false,Would buy again without hesitation.,9.4,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20295,19842,Frank N.,27.0,9999999,2010-06-21,engineering,Female,U.K.,Chittagong,93.7,False,Delivery was fast and packaging great.,$199.19,NaN,0
20296,1769,Frank N.,45.0,31616,2021-01-11,hr,F,U.K.,Khulna,NaN,False,Product met all expectations.,223.39,NaN,0
20297,9930,Hasan A.,30.0,70125,2013-07-07,Engineering,Woman,bd,Khulna,116.3,True,Would buy again without hesitation.,68.16,NaN,0
20298,3241,Frank D.,58.0,40120,2022-03-25,SALES,M,UK,Rajshahi,72.0,True,NaN,90.83,NaN,0
20299,13498,Alice X.,NaN,114722,2023-08-12,HR,Man,UK,Khulna,74.0,False,NaN,142.13,NaN,0

In [188]:
df.shape

(20300, 15)

In [189]:
df1=df.copy()

In [190]:
df.dtypes

employee_id              int64
name                    object
age                    float64
salary                  object
join_date               object
department              object
gender                  object
country                 object
city                    object
weight_kg               object
is_active               object
review                  object
price                   object
weight_kg_duplicate    float64
target                   int64
dtype: object

In [191]:
df.isnull().sum()

employee_id                0
name                       0
age                      621
salary                   610
join_date                810
department               857
gender                  1632
country                  608
city                     604
weight_kg                643
is_active                586
review                  1465
price                    446
weight_kg_duplicate    20300
target                     0
dtype: int64

## Task 01: Missing Values (NaN, Empty Strings)

**Problem:**  
A column may have missing values (NaN or empty strings).

These missing values create issues in data visualization.

In [192]:
df.isnull().sum()

employee_id                0
name                       0
age                      621
salary                   610
join_date                810
department               857
gender                  1632
country                  608
city                     604
weight_kg                643
is_active                586
review                  1465
price                    446
weight_kg_duplicate    20300
target                     0
dtype: int64

In [193]:
df

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
0,12369,Hasan D.,200.0,35149,2023-05-30,SALES,Man,America,Sylhet,118.4,0,Good value for money.,219.18,NaN,0
1,7361,Grace P.,NaN,77836,2017-02-27,Engineering,FEMALE,America,Chittagong,71kg,True,Product met all expectations.,329.26,NaN,0
2,3446,Eve D.,20.0,35404,2022-01-18,hr,male,BANGLADESH,Chitagong,98.7,False,Very satisfied with the quality.,438.6,NaN,0
3,18416,Diana E.,47.0,107375,2017-04-15,Marketing,Male,U.K.,Khulna,NaN,false,Delivery was fast and packaging great.,238.03,NaN,0
4,13677,Ira W.,64.0,55962,2021-11-02,SALES,F,United Kingdom,Dhaka,83.5,false,Would buy again without hesitation.,9.4,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20295,19842,Frank N.,27.0,9999999,2010-06-21,engineering,Female,U.K.,Chittagong,93.7,False,Delivery was fast and packaging great.,$199.19,NaN,0
20296,1769,Frank N.,45.0,31616,2021-01-11,hr,F,U.K.,Khulna,NaN,False,Product met all expectations.,223.39,NaN,0
20297,9930,Hasan A.,30.0,70125,2013-07-07,Engineering,Woman,bd,Khulna,116.3,True,Would buy again without hesitation.,68.16,NaN,0
20298,3241,Frank D.,58.0,40120,2022-03-25,SALES,M,UK,Rajshahi,72.0,True,NaN,90.83,NaN,0
20299,13498,Alice X.,NaN,114722,2023-08-12,HR,Man,UK,Khulna,74.0,False,NaN,142.13,NaN,0

In [194]:
df['salary']=pd.to_numeric(df['salary'],errors='coerce')

In [195]:
df['salary']

0          35149.0
1          77836.0
2          35404.0
3         107375.0
4          55962.0
           ...
20295    9999999.0
20296      31616.0
20297      70125.0
20298      40120.0
20299     114722.0
Name: salary, Length: 20300, dtype: float64

In [196]:
df['price']

0         219.18
1         329.26
2          438.6
3         238.03
4            9.4
          ...
20295    $199.19
20296     223.39
20297      68.16
20298      90.83
20299     142.13
Name: price, Length: 20300, dtype: object

In [197]:
df["price"] = (
    df["price"]
    .astype(str)
    .str.replace("$", "", regex=False)
)

df["price"] = pd.to_numeric(df["price"], errors="coerce")

In [198]:
df['price']

0        219.18
1        329.26
2        438.60
3        238.03
4          9.40
          ...
20295    199.19
20296    223.39
20297     68.16
20298     90.83
20299    142.13
Name: price, Length: 20300, dtype: float64

In [199]:
df['weight_kg']

0        118.4
1         71kg
2         98.7
3          NaN
4         83.5
         ...
20295     93.7
20296      NaN
20297    116.3
20298     72.0
20299     74.0
Name: weight_kg, Length: 20300, dtype: object

In [200]:
df["weight_kg"] = (
    df["weight_kg"]
    .astype(str)
    .str.replace("kg", "", regex=False)
)

In [201]:
df["weight_kg"] = pd.to_numeric(df["weight_kg"], errors="coerce")

In [202]:
df["age"] = df["age"].fillna(df["age"].median())
df["salary"] = df["salary"].fillna(df["salary"].median())
df["price"] = df["price"].fillna(df["price"].median())
df["weight_kg"] = df["weight_kg"].fillna(df["weight_kg"].median())

In [203]:
df.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                810
department               857
gender                  1632
country                  608
city                     604
weight_kg                  0
is_active                586
review                  1465
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

In [204]:
df['department']

0              SALES
1        Engineering
2                 hr
3          Marketing
4              SALES
            ...
20295    engineering
20296             hr
20297    Engineering
20298          SALES
20299             HR
Name: department, Length: 20300, dtype: object

In [205]:
df['department']=df['department'].fillna(df['department'].mode()[0])

In [206]:
df['department'].isnull().sum()

0

In [207]:
df['gender']

0           Man
1        FEMALE
2          male
3          Male
4             F
          ...
20295    Female
20296         F
20297     Woman
20298         M
20299       Man
Name: gender, Length: 20300, dtype: object

In [208]:
df['gender']=df['gender'].fillna(df['gender'].mode()[0])

In [209]:
df['gender'].isnull().sum()

0

In [210]:
df['country']

0               America
1               America
2            BANGLADESH
3                  U.K.
4        United Kingdom
              ...
20295              U.K.
20296              U.K.
20297                bd
20298                UK
20299                UK
Name: country, Length: 20300, dtype: object

In [211]:
df['country']=df['country'].fillna(df['country'].mode()[0])

In [212]:
df['country'].isnull().sum()

0

In [213]:
df['city']=df['city'].fillna(df['city'].mode()[0])

In [214]:
df.dtypes

employee_id              int64
name                    object
age                    float64
salary                 float64
join_date               object
department              object
gender                  object
country                 object
city                    object
weight_kg              float64
is_active               object
review                  object
price                  float64
weight_kg_duplicate    float64
target                   int64
dtype: object

In [215]:
df['join_date']

0        2023-05-30
1        2017-02-27
2        2022-01-18
3        2017-04-15
4        2021-11-02
            ...
20295    2010-06-21
20296    2021-01-11
20297    2013-07-07
20298    2022-03-25
20299    2023-08-12
Name: join_date, Length: 20300, dtype: object

In [240]:
df["join_date"] = pd.to_datetime(
    df["join_date"],
    errors="coerce"
)

In [241]:
df["join_date"] = df["join_date"].fillna(df["join_date"].mode()[0])

In [218]:
df["review"] = df["review"].fillna("No Review")

In [219]:
df['is_active']

0            0
1         True
2        False
3        false
4        false
         ...
20295    False
20296    False
20297     True
20298     True
20299    False
Name: is_active, Length: 20300, dtype: object

In [220]:
df["is_active"] = df["is_active"].map({
    "True":True,
    "False":False
})

In [221]:
df['is_active']=df['is_active'].fillna(False)

C:\Users\HP\AppData\Local\Temp\ipykernel_11212\4292727086.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['is_active']=df['is_active'].fillna(False)

In [222]:
df.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                  0
department                 0
gender                     0
country                    0
city                       0
weight_kg                  0
is_active                  0
review                     0
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

In [223]:
df.drop(columns=['weight_kg_duplicate'], inplace=True)

In [224]:
df.isnull().sum()

employee_id    0
name           0
age            0
salary         0
join_date      0
department     0
gender         0
country        0
city           0
weight_kg      0
is_active      0
review         0
price          0
target         0
dtype: int64


## Solutions

Drop rows

Drop columns

Mean Imputation

Median Imputation

Mode Imputation

Forward Fill

Backward Fill

## Task 02 :Duplicate Rows

**Problem:**

Same type rows consume memory which is bad and unnecessary for our analysis.

So, we have to drop duplicate rows.

In [225]:
df.duplicated().sum()

300

In [226]:
df[df.duplicated()]

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,target
1302,10364,Frank O.,24.0,112578.0,2010-09-10,HR,M,BD,Dhka,95.8,True,Delivery was fast and packaging great.,22.75,0
1834,16035,Hasan V.,53.0,-500.0,2017-03-01,Marketing,female,BANGLADESH,Chittagong,48.2,False,Product met all expectations.,385.13,0
2338,12369,Hasan D.,200.0,35149.0,2023-05-30,SALES,Man,America,Sylhet,118.4,False,Good value for money.,219.18,0
2469,13108,Diana V.,43.0,88859.0,2023-06-09,Marketing,Male,United States,Khulna,73.8,True,good,430.17,0
2784,7983,Grace G.,32.0,75294.0,2023-06-09,engineering,Man,U.K.,Khulna,60.2,True,"Excellent product, highly recommend!",237.72,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20110,13509,Charlie S.,34.0,106326.0,2016-06-20,Finace,Man,U.S.A,Slyhet,112.3,False,fine,340.03,0
20140,2388,Eve A.,35.0,98091.0,2017-04-22,SALES,M,America,Slyhet,90.4,False,Good value for money.,451.34,0
20154,2689,John O.,46.0,45615.0,2023-06-09,hr,F,usa,Rajshahi,118.0,False,Would buy again without hesitation.,341.28,0
20173,5188,Charlie J.,46.0,75294.0,2017-04-03,HR,Male,BANGLADESH,Chittagong,73.0,True,bad,419.32,0
20227,4518,Grace R.,54.0,66484.0,2023-06-09,Marketing,M,BANGLADESH,Khulna,116.2,True,Product met all expectations.,249.01,0

In [227]:
df.drop_duplicates(inplace=True)

In [228]:
df1.shape

(20300, 15)

In [229]:
df.shape

(20000, 14)

In [230]:
df2=df.copy()

**Solutions:**

 Run df.duplicated().sum() to count duplicates.

 Preview duplicates: df[df.duplicated()]

 Remove duplicates: df.drop_duplicates(inplace=True)

 Verify: compare df.shape before and after.
 

Finally ,duplicate rows was no more

## Task 03 Duplicate IDs

**Problem**

In a particular column there might be duplicate rows.

It creates memory loss.

In [231]:
df['employee_id'].duplicated().sum()

199

In [232]:
df[df['employee_id'].duplicated(keep=False)]

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,target
29,250,Frank U.,56.0,90635.0,2013-05-12,Sales,male,Bangladesh,Dhaka,107.3,False,Would buy again without hesitation.,342.24,1
40,49,John L.,58.0,50810.0,2024-07-22,hr,FEMALE,U.K.,Dhakka,108.8,False,"Excellent product, highly recommend!",83.46,0
75,48,Ira E.,0.0,101013.0,2013-08-28,engineering,MALE,BD,Dhakka,115.0,False,Good value for money.,318.78,0
196,436,Charlie S.,29.0,54295.0,2020-08-27,Mrketing,M,us,Chittagongg,75.9,False,Product met all expectations.,265.25,0
270,86,Bob U.,36.0,61688.0,2023-06-09,engineering,M,bd,Sylhet,91.7,False,na,167.05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20016,207,Bob M.,63.0,73657.0,2013-10-08,Mrketing,M,USA,Rajshahi,125.5,False,Very satisfied with the quality.,167.18,0
20072,435,Charlie U.,31.0,112727.0,2016-04-15,engineering,MALE,U.K.,Rajshahi,119.0,False,Good value for money.,242.44,0
20104,427,Frank U.,33.0,35686.0,2014-03-21,Mrketing,M,usa,Rajshahi,73.8,True,Good value for money.,396.43,0
20267,35,Eve L.,55.0,40160.0,2015-12-13,Finance,Male,U.K.,Dhaka,61.0,True,Very satisfied with the quality.,106.40,0
20289,289,Frank C.,58.0,95829.0,2011-10-28,HR,Woman,United States,Khulna,93.2,True,Very satisfied with the quality.,123.17,0

In [233]:
df.drop_duplicates(subset=['employee_id'], keep='first')

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,target
0,12369,Hasan D.,200.0,35149.0,2023-05-30,SALES,Man,America,Sylhet,118.4,False,Good value for money.,219.18,0
1,7361,Grace P.,41.0,77836.0,2017-02-27,Engineering,FEMALE,America,Chittagong,71.0,True,Product met all expectations.,329.26,0
2,3446,Eve D.,20.0,35404.0,2022-01-18,hr,male,BANGLADESH,Chitagong,98.7,False,Very satisfied with the quality.,438.60,0
3,18416,Diana E.,47.0,107375.0,2017-04-15,Marketing,Male,U.K.,Khulna,86.8,False,Delivery was fast and packaging great.,238.03,0
4,13677,Ira W.,64.0,55962.0,2021-11-02,SALES,F,United Kingdom,Dhaka,83.5,False,Would buy again without hesitation.,9.40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20295,19842,Frank N.,27.0,9999999.0,2010-06-21,engineering,Female,U.K.,Chittagong,93.7,False,Delivery was fast and packaging great.,199.19,0
20296,1769,Frank N.,45.0,31616.0,2021-01-11,hr,F,U.K.,Khulna,86.8,False,Product met all expectations.,223.39,0
20297,9930,Hasan A.,30.0,70125.0,2013-07-07,Engineering,Woman,bd,Khulna,116.3,True,Would buy again without hesitation.,68.16,0
20298,3241,Frank D.,58.0,40120.0,2022-03-25,SALES,M,UK,Rajshahi,72.0,True,No Review,90.83,0
20299,13498,Alice X.,41.0,114722.0,2023-08-12,HR,Man,UK,Khulna,74.0,False,No Review,142.13,0

In [234]:
df['employee_id'] = range(1, len(df)+1)

In [235]:
assert df['employee_id'].duplicated().sum() == 0

**Solution**

 Count: df['employee_id'].duplicated().sum()

View: df[df['employee_id'].duplicated(keep=False)]

Option A: keep first occurrence — df.drop_duplicates(subset=['employee_id'], keep='first')

 Option B: assign new unique IDs — df['employee_id'] = range(1, len(df)+1)
 
 Verify: assert df['employee_id'].duplicated().sum() == 0

## Task 04: Wrong Date Formats

**Problem:**

5 mixed formats: YYYY-MM-DD, DD/MM/YYYY, MM-DD-YYYY, DD-Mon-YYYY

Because of this we can't find which was date ,which was month ,which was year.

In [242]:
df['join_date'].dtype

dtype('<M8[ns]')

## Solution

Check dtype: df['join_date'].dtype — will be object.

Convert: pd.to_datetime(df['join_date'], infer_datetime_format=True, errors='coerce')

errors='coerce' turns unrecognized formats into NaT.

Handle NaT values: fill with median date.

Standardize output: df['join_date'].dt.strftime('%Y-%m-%d')

Verify dtype: df['join_date'].dtype — should be datetime64.

Already this was done in the above.

## Task 05 :Numeric Stored as String

**Problem**

In this case ,we cannot do any mathematical operation if the numerical column is treated as string/obj.

In [243]:
df['salary'].dtype

dtype('float64')

In [244]:
df['weight_kg'].dtype

dtype('float64')

In [245]:
df['price'].dtype

dtype('float64')

## Already done above