In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df1=df.copy

In [4]:
df1

<bound method NDFrame.copy of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [5]:
df.to_csv('output.csv',index=False)

In [6]:
d=pd.read_csv('output.csv')

In [8]:
d

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [8]:
df.loc[0,'Name']

'Braund, Mr. Owen Harris'

In [9]:
df.iloc[0,3]

'Braund, Mr. Owen Harris'

In [10]:
df.loc[1:3,'Name':'Age']

                                                Name     Sex   Age
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0

In [11]:
df.iloc[0:3,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3

In [12]:
df[df['Age']>21]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [13]:
df3=df[df['Name'].isin(['Braund, Mr. Owen Harris', 'Heikkinen, Miss. Laina'])]
df3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S

In [14]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
ddd=df.dropna()

In [16]:
ddd.shape

(183, 12)

In [17]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
# Now rest part
df = pd.DataFrame({
    'Name': ['Rahim', 'Karim', 'Sadia', 'Mim'],
    'Age': [20, 22, 21, 23],
    'Score': [85, 90, 78, 92]
})

print(df)

    Name  Age  Score
0  Rahim   20     85
1  Karim   22     90
2  Sadia   21     78
3    Mim   23     92

In [19]:
df['Score'].mean()

86.25

In [20]:
df['Score'].sum()

345

In [21]:
df['Score'].count()

4

In [22]:
df['Score'].min()

78

In [23]:
df['Score'].max()

92

In [24]:
df['Score'].median()

87.5

In [25]:
df['Score'].describe()

count     4.000000
mean     86.250000
std       6.238322
min      78.000000
25%      83.250000
50%      87.500000
75%      90.500000
max      92.000000
Name: Score, dtype: float64

In [26]:
df.agg({
    'Age': ['mean', 'min', 'max'],
    'Score': ['mean', 'std']
})

       Age      Score
mean  21.5  86.250000
min   20.0        NaN
max   23.0        NaN
std    NaN   6.238322

In [27]:
# Groupby

In [35]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Rahim', 'Karim', 'Mim', 'Sadia', 'Nayeem'],
    'Department': ['IT', 'HR', 'IT', 'HR', 'IT'],
    'Gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
    'Salary': [50000, 40000, 60000, 45000, 55000],
    'Age': [22, 25, 23, None, 26]
})

print(df)

     Name Department  Gender  Salary   Age
0   Rahim         IT    Male   50000  22.0
1   Karim         HR    Male   40000  25.0
2     Mim         IT  Female   60000  23.0
3   Sadia         HR  Female   45000   NaN
4  Nayeem         IT    Male   55000  26.0

In [36]:
df.groupby('Department')['Salary'].mean()

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [37]:
df.groupby('Department').agg({
    'Salary':['mean','max'],
    'Age':'count'
    
})

             Salary          Age
               mean    max count
Department
HR          42500.0  45000     1
IT          55000.0  60000     3

In [38]:
df.groupby(['Department', 'Gender'])['Salary'].mean()

Department  Gender
HR          Female    45000.0
            Male      40000.0
IT          Female    60000.0
            Male      52500.0
Name: Salary, dtype: float64

In [39]:
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'Name': ['Rahim', 'Karim', 'Mim']
})

print(df1)

   id   Name
0   1  Rahim
1   2  Karim
2   3    Mim

In [40]:
df2 = pd.DataFrame({
    'id': [2, 3, 4],
    'Salary': [40000, 50000, 60000]
})

print(df2)

   id  Salary
0   2   40000
1   3   50000
2   4   60000

In [41]:
pd.merge(df1, df2, on='id', how='inner')

   id   Name  Salary
0   2  Karim   40000
1   3    Mim   50000

In [42]:
pd.merge(df1, df2, on='id', how='left')

   id   Name   Salary
0   1  Rahim      NaN
1   2  Karim  40000.0
2   3    Mim  50000.0

In [43]:
pd.merge(df1, df2, on='id', how='right')

   id   Name  Salary
0   2  Karim   40000
1   3    Mim   50000
2   4    NaN   60000

In [44]:
pd.merge(df1, df2, on='id', how='outer')

   id   Name   Salary
0   1  Rahim      NaN
1   2  Karim  40000.0
2   3    Mim  50000.0
3   4    NaN  60000.0

In [45]:
pd.merge(
    df1,
    df2,
    left_on='user_id',
    right_on='id',
    how='left'
)

KeyError: 'user_id'

In [46]:
df1 = pd.DataFrame({
    'Name': ['Rahim', 'Karim']
})

df2 = pd.DataFrame({
    'Name': ['Mim', 'Sadia']
})

pd.concat([df1, df2])

    Name
0  Rahim
1  Karim
0    Mim
1  Sadia

In [47]:
pd.concat([df1, df2], ignore_index=True)

    Name
0  Rahim
1  Karim
2    Mim
3  Sadia

In [50]:
df1 = pd.DataFrame({
    'Name': ['Rahim', 'Karim','Sayem']
}, index=[1,2,3])

df2 = pd.DataFrame({
    'Salary': [50000, 60000]
}, index=[1,2])

df1.join(df2)

    Name   Salary
1  Rahim  50000.0
2  Karim  60000.0
3  Sayem      NaN

In [51]:
df1.join(df2, how='outer')

    Name   Salary
1  Rahim  50000.0
2  Karim  60000.0
3  Sayem      NaN