In [1]:
import pandas as pd
df=pd.read_csv('D:\AI-ML SC\AI---Ml-\Garment_Job_Risk.csv')

<>:2: SyntaxWarning: invalid escape sequence '\A'
<>:2: SyntaxWarning: invalid escape sequence '\A'
C:\Users\HP\AppData\Local\Temp\ipykernel_24284\280377961.py:2: SyntaxWarning: invalid escape sequence '\A'
  df=pd.read_csv('D:\AI-ML SC\AI---Ml-\Garment_Job_Risk.csv')

In [2]:
df

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
0,Taslima Akter,Pallmall Group,38,Packaging,41,Medium,Light,Average,2,Healthy,Basic,Day,Occasional,Low
1,Rasel Hossain,Pallmall Group,28,Packaging,51,Low,Light,Average,0,Minor_Chronic,Basic,Day,Frequent,Low
2,Abdul Latif,Pallmall Group,14,Supervisor,68,Low,NaN,Average,0,Healthy,NaN,Night,Frequent,Medium
3,Nazia Sultana,Pallmall Group,7,Sewing,28,High,NaN,Average,0,Healthy,Basic,Day,Occasional,Low
4,Nazia Sultana,Pallmall Group,20,Packaging,49,NaN,Light,Average,0,Healthy,Advanced,Day,Frequent,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,Shamina Begum,Pallmall Group,18,Dyeing,32,NaN,Heavy,Average,0,Healthy,Basic,Day,Occasional,Medium
2496,Fariha Khan,Pallmall Group,30,Dyeing,40,Medium,Light,Average,1,Healthy,Basic,Day,Frequent,Medium
2497,Fariha Khan,Pallmall Group,18,Packaging,55,High,Light,Poor,2,Healthy,NaN,Night,Occasional,High
2498,Mushfiqur Rahman,Pallmall Group,18,Cutting,52,High,Light,Average,0,Minor_Chronic,Basic,Day,Occasional,Low
2499,Mushfiqur Rahman,Pallmall Group,21,Packaging,62,Medium,NaN,Average,1,Minor_Chronic,Basic,Day,Occasional,Low

In [3]:
df.shape

(2500, 14)

In [4]:
dataset1=df.copy()

In [5]:
dataset1

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
0,Taslima Akter,Pallmall Group,38,Packaging,41,Medium,Light,Average,2,Healthy,Basic,Day,Occasional,Low
1,Rasel Hossain,Pallmall Group,28,Packaging,51,Low,Light,Average,0,Minor_Chronic,Basic,Day,Frequent,Low
2,Abdul Latif,Pallmall Group,14,Supervisor,68,Low,NaN,Average,0,Healthy,NaN,Night,Frequent,Medium
3,Nazia Sultana,Pallmall Group,7,Sewing,28,High,NaN,Average,0,Healthy,Basic,Day,Occasional,Low
4,Nazia Sultana,Pallmall Group,20,Packaging,49,NaN,Light,Average,0,Healthy,Advanced,Day,Frequent,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,Shamina Begum,Pallmall Group,18,Dyeing,32,NaN,Heavy,Average,0,Healthy,Basic,Day,Occasional,Medium
2496,Fariha Khan,Pallmall Group,30,Dyeing,40,Medium,Light,Average,1,Healthy,Basic,Day,Frequent,Medium
2497,Fariha Khan,Pallmall Group,18,Packaging,55,High,Light,Poor,2,Healthy,NaN,Night,Occasional,High
2498,Mushfiqur Rahman,Pallmall Group,18,Cutting,52,High,Light,Average,0,Minor_Chronic,Basic,Day,Occasional,Low
2499,Mushfiqur Rahman,Pallmall Group,21,Packaging,62,Medium,NaN,Average,1,Minor_Chronic,Basic,Day,Occasional,Low

In [6]:
df.describe()

       Experience_Years  Working_Hours_Per_Week  Injury_History
count       2500.000000             2500.000000     2500.000000
mean          20.248800               48.027600        0.579200
std           11.832214               11.702548        0.761025
min            0.000000               28.000000        0.000000
25%           10.000000               38.000000        0.000000
50%           21.000000               48.000000        0.000000
75%           31.000000               58.000000        1.000000
max           40.000000               68.000000        6.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     2500 non-null   object
 1   Garment_Name             2500 non-null   object
 2   Experience_Years         2500 non-null   int64
 3   Job_Role                 2500 non-null   object
 4   Working_Hours_Per_Week   2500 non-null   int64
 5   Exposure_To_Chemicals    1276 non-null   object
 6   Machine_Use              2046 non-null   object
 7   Workstation_Ergonomics   2500 non-null   object
 8   Injury_History           2500 non-null   int64
 9   Health_Condition         2500 non-null   object
 10  Safety_Training          2062 non-null   object
 11  Shift_Type               2500 non-null   object
 12  Task_Rotation_Frequency  2500 non-null   object
 13  Job_Risk                 2500 non-null   object
dtypes: int64(3), object(11)
memory usage: 273.6+ KB

In [8]:
df.isnull().sum()

Name                          0
Garment_Name                  0
Experience_Years              0
Job_Role                      0
Working_Hours_Per_Week        0
Exposure_To_Chemicals      1224
Machine_Use                 454
Workstation_Ergonomics        0
Injury_History                0
Health_Condition              0
Safety_Training             438
Shift_Type                    0
Task_Rotation_Frequency       0
Job_Risk                      0
dtype: int64

In [12]:
df.duplicated().sum()

0

Data Type Conversion

In [7]:
import pandas as pd

# Sample DataFrame

In [8]:
df = pd.DataFrame({    'price': ['100', '250', 'abc', '400'],
    'date': ['2025-01-10', '2025-02-15', '2025-03-20', '2025-04-25'],
    'city': ['Dhaka', 'Sylhet', 'Dhaka', 'Chittagong'],
    'quantity': [1.0, 2.0, 3.0, 4.0]
})

print("Original DataFrame:\n")
print(df)

Original DataFrame:

  price        date        city  quantity
0   100  2025-01-10       Dhaka       1.0
1   250  2025-02-15      Sylhet       2.0
2   abc  2025-03-20       Dhaka       3.0
3   400  2025-04-25  Chittagong       4.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     4 non-null      object
 1   date      4 non-null      object
 2   city      4 non-null      object
 3   quantity  4 non-null      float64
dtypes: float64(1), object(3)
memory usage: 260.0+ bytes

In [3]:
df['price']=pd.to_numeric(df['price'],errors='coerce')
print(df)

   price        date        city  quantity
0  100.0  2025-01-10       Dhaka       1.0
1  250.0  2025-02-15      Sylhet       2.0
2    NaN  2025-03-20       Dhaka       3.0
3  400.0  2025-04-25  Chittagong       4.0

In [11]:
df['date']=pd.to_datetime(df['date'])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   price     4 non-null      object
 1   date      4 non-null      datetime64[ns]
 2   city      4 non-null      object
 3   quantity  4 non-null      float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 260.0+ bytes

In [15]:
print(df['date'].dt.date)

0    2025-01-10
1    2025-02-15
2    2025-03-20
3    2025-04-25
Name: date, dtype: object

In [16]:
df

  price       date        city  quantity
0   100 2025-01-10       Dhaka       1.0
1   250 2025-02-15      Sylhet       2.0
2   abc 2025-03-20       Dhaka       3.0
3   400 2025-04-25  Chittagong       4.0

In [17]:
df['city']=df['city'].astype('category')
print(df['city'].dtype)

category

In [19]:
df['quantity']=df['quantity'].astype('int')
print(df['quantity'].dtype)

int32

Duplicate Removal

In [23]:
df = pd.DataFrame({
    'student_id': [1, 2, 2, 3, 3, 3,1],
    'name': ['Asha', 'Rahim', 'Rahim', 'Karim', 'Karim', 'Karim','Asha'],
    'marks': [80, 90, 90, 70, 75, 75,80],
    'updated_at': ['2025-01-01', '2025-02-01', '2025-03-01',
                   '2025-01-10', '2025-02-10', '2025-03-10','2025-01-01']
})

print(df)

   student_id   name  marks  updated_at
0           1   Asha     80  2025-01-01
1           2  Rahim     90  2025-02-01
2           2  Rahim     90  2025-03-01
3           3  Karim     70  2025-01-10
4           3  Karim     75  2025-02-10
5           3  Karim     75  2025-03-10
6           1   Asha     80  2025-01-01

1. Exact Duplicate Removal (all columns same)

In [24]:
df1=df.drop_duplicates()
print(df1)

   student_id   name  marks  updated_at
0           1   Asha     80  2025-01-01
1           2  Rahim     90  2025-02-01
2           2  Rahim     90  2025-03-01
3           3  Karim     70  2025-01-10
4           3  Karim     75  2025-02-10
5           3  Karim     75  2025-03-10

2. Duplicate Removal by Key Column (student_id)

In [25]:
df2 = df.drop_duplicates(subset='student_id', keep='first')

In [26]:
df3 = df.drop_duplicates(subset='student_id', keep='last')

print(df3)

   student_id   name  marks  updated_at
2           2  Rahim     90  2025-03-01
5           3  Karim     75  2025-03-10
6           1   Asha     80  2025-01-01

3. Business Logic: Keep Latest Record (based on date)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  7 non-null      int64
 1   name        7 non-null      object
 2   marks       7 non-null      int64
 3   updated_at  7 non-null      object
dtypes: int64(2), object(2)
memory usage: 356.0+ bytes

In [30]:
df['updated_at']=pd.to_datetime(df['updated_at'])
df4=df.sort_values('updated_at').drop_duplicates(subset='student_id',keep='last')
print(df)
print(df4)

   student_id   name  marks updated_at
0           1   Asha     80 2025-01-01
1           2  Rahim     90 2025-02-01
2           2  Rahim     90 2025-03-01
3           3  Karim     70 2025-01-10
4           3  Karim     75 2025-02-10
5           3  Karim     75 2025-03-10
6           1   Asha     80 2025-01-01
   student_id   name  marks updated_at
6           1   Asha     80 2025-01-01
2           2  Rahim     90 2025-03-01
5           3  Karim     75 2025-03-10

4. Threshold-Based Filtering (keep max 2 occurrences)

In [31]:
df5 = df.groupby('student_id').head(2)

print(df5)

   student_id   name  marks updated_at
0           1   Asha     80 2025-01-01
1           2  Rahim     90 2025-02-01
2           2  Rahim     90 2025-03-01
3           3  Karim     70 2025-01-10
4           3  Karim     75 2025-02-10
6           1   Asha     80 2025-01-01

STRING OPERATIONS FOR TEXT CLEANING

In [32]:
df = pd.DataFrame({
    'name': ['  Alice ', 'BOB', 'charlie!!', 'DaVid  ', 'Eve@123'],
    'gender': [' Male', 'FEMALE ', 'male', 'FeMale', ' MALE'],
    'email': ['alice@gmail.com', 'bob@@mail.com', 'charlie@gmail.com',
              'david@gmail.com ', 'eve#gmail.com']
})

print(df)

        name   gender              email
0     Alice      Male    alice@gmail.com
1        BOB  FEMALE       bob@@mail.com
2  charlie!!     male  charlie@gmail.com
3    DaVid     FeMale   david@gmail.com
4    Eve@123     MALE      eve#gmail.com

1. Strip spaces (leading/trailing)

In [33]:
df['name'] = df['name'].str.strip()
df['gender'] = df['gender'].str.strip()
df['email'] = df['email'].str.strip()

print(df)

        name  gender              email
0      Alice    Male    alice@gmail.com
1        BOB  FEMALE      bob@@mail.com
2  charlie!!    male  charlie@gmail.com
3      DaVid  FeMale    david@gmail.com
4    Eve@123    MALE      eve#gmail.com

2. Lowercase normalization

In [34]:
df['name'] = df['name'].str.lower()
df['gender'] = df['gender'].str.lower()

print(df)

        name  gender              email
0      alice    male    alice@gmail.com
1        bob  female      bob@@mail.com
2  charlie!!    male  charlie@gmail.com
3      david  female    david@gmail.com
4    eve@123    male      eve#gmail.com

3. Remove special characters (regex cleaning)

In [35]:
df['name'] = df['name'].str.replace(r'[^a-zA-Z ]', '', regex=True)
df['email'] = df['email'].str.replace(r'[^a-zA-Z0-9@.]', '', regex=True)

print(df)

      name  gender              email
0    alice    male    alice@gmail.com
1      bob  female      bob@@mail.com
2  charlie    male  charlie@gmail.com
3    david  female    david@gmail.com
4      eve    male       evegmail.com

4. Title case formatting (optional)

In [36]:
df['name'] = df['name'].str.title()

print(df)

      name  gender              email
0    Alice    male    alice@gmail.com
1      Bob  female      bob@@mail.com
2  Charlie    male  charlie@gmail.com
3    David  female    david@gmail.com
4      Eve    male       evegmail.com

5. Split combined column (example)

In [41]:
df2 = pd.DataFrame({
    'full_name': ['John Doe', 'Alice Smith', 'Bob Marley']
})

# df2[['first_name', 'last_name']] = df2['full_name'].str.split(' ',expand=True)


print(df2['full_name'].str.split(' '))

0       [John, Doe]
1    [Alice, Smith]
2     [Bob, Marley]
Name: full_name, dtype: object

6. Filter by pattern (regex search)

In [42]:
gmail_users = df[df['email'].str.contains('gmail', regex=True)]

print(gmail_users)

      name  gender              email
0    Alice    male    alice@gmail.com
2  Charlie    male  charlie@gmail.com
3    David  female    david@gmail.com
4      Eve    male       evegmail.com

Full cleaning workflow

In [78]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({
    'student_id': [1, 2, 2, 3, 4, 5],
    'name': [' Alice ', 'BOB', 'bob', 'Charlie!!', 'David', 'Eve@123'],
    'age': ['20', '21', '21', None, '200', '19'],
    'marks': [80, 90, 90, 70, 150, None],
    'join_date': ['2025-01-10', '2025-02-15', '2025-02-15',
                  '2025-03-20', '2025-04-01', '2025-05-01']
})
df=df1.copy()

print(df)

   student_id       name   age  marks   join_date
0           1     Alice     20   80.0  2025-01-10
1           2        BOB    21   90.0  2025-02-15
2           2        bob    21   90.0  2025-02-15
3           3  Charlie!!  None   70.0  2025-03-20
4           4      David   200  150.0  2025-04-01
5           5    Eve@123    19    NaN  2025-05-01

STEP 1: Inspect Data

In [79]:
df.shape

(6, 5)

In [1]:
df.info()
print("do")

NameError: name 'df' is not defined

In [81]:
df.isnull().sum()

student_id    0
name          0
age           1
marks         1
join_date     0
dtype: int64

STEP 2: Fix Data Types

In [ ]:
df['age']=pd.to_numeric(df['age'],errors='coerce')
df['join_date'] = pd.to_datetime(df['join_date'])

p

d

In [83]:
df

   student_id       name    age  marks  join_date
0           1     Alice    20.0   80.0 2025-01-10
1           2        BOB   21.0   90.0 2025-02-15
2           2        bob   21.0   90.0 2025-02-15
3           3  Charlie!!    NaN   70.0 2025-03-20
4           4      David  200.0  150.0 2025-04-01
5           5    Eve@123   19.0    NaN 2025-05-01

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  6 non-null      int64
 1   name        6 non-null      object
 2   age         5 non-null      float64
 3   marks       5 non-null      float64
 4   join_date   6 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 372.0+ bytes

STEP 3: Handle Missing Values

In [85]:
df.isnull().sum()

student_id    0
name          0
age           1
marks         1
join_date     0
dtype: int64

In [86]:

df

   student_id       name    age  marks  join_date
0           1     Alice    20.0   80.0 2025-01-10
1           2        BOB   21.0   90.0 2025-02-15
2           2        bob   21.0   90.0 2025-02-15
3           3  Charlie!!    NaN   70.0 2025-03-20
4           4      David  200.0  150.0 2025-04-01
5           5    Eve@123   19.0    NaN 2025-05-01

In [106]:
# IQR
Q1=df['marks'].quantile(0.25)
Q3=df['marks'].quantile(0.75)
IQR=Q3-Q1
l=Q1-1.5*IQR
h=Q3+1.5*IQR
print(f"{l} {h}")

65.0 105.0

In [ ]:


df['age']=df['age'].fillna(df['age'].median())
df['marks'] = df['marks'].fillna(df['marks'].median())

In [88]:
df

   student_id       name    age  marks  join_date
0           1     Alice    20.0   80.0 2025-01-10
1           2        BOB   21.0   90.0 2025-02-15
2           2        bob   21.0   90.0 2025-02-15
3           3  Charlie!!   21.0   70.0 2025-03-20
4           4      David  200.0  150.0 2025-04-01
5           5    Eve@123   19.0   90.0 2025-05-01

STEP 4: Remove Duplicates

In [89]:
df = df.drop_duplicates(subset='student_id', keep='first')

STEP 5: Detect & Treat Outliers (IQR method)

In [90]:
Q1 = df['marks'].quantile(0.25)
Q3 = df['marks'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-IQR*1.5
upper=Q3+IQR*1.5
# Capping (Winsorization)
df=df.copy()
df['marks']=np.where(df['marks']>upper,upper,
                     np.where(df['marks']<lower,lower,df['marks']))

STEP 6: Clean Text Columns

In [91]:
df

   student_id       name    age  marks  join_date
0           1     Alice    20.0   80.0 2025-01-10
1           2        BOB   21.0   90.0 2025-02-15
3           3  Charlie!!   21.0   70.0 2025-03-20
4           4      David  200.0  105.0 2025-04-01
5           5    Eve@123   19.0   90.0 2025-05-01

In [92]:
df['name']=df['name'].str.strip()

In [99]:
df

   student_id     name    age  marks  join_date
0           1    Alice   20.0   80.0 2025-01-10
1           2      Bob   21.0   90.0 2025-02-15
3           3  Charlie   21.0   70.0 2025-03-20
4           4    David  200.0  105.0 2025-04-01
5           5      Eve   19.0   90.0 2025-05-01

In [94]:
df['name'] = df['name'].str.lower()

In [96]:
df['name'] = df['name'].str.replace(r'[^a-z ]', '', regex=True)

In [98]:
df['name'] = df['name'].str.title()

In [100]:
print(df.shape)
print(df.isnull().sum())
print(df.dtypes)
print(df.describe())

(5, 5)
student_id    0
name          0
age           0
marks         0
join_date     0
dtype: int64
student_id             int64
name                  object
age                  float64
marks                float64
join_date     datetime64[ns]
dtype: object
       student_id        age       marks            join_date
count    5.000000    5.00000    5.000000                    5
mean     3.000000   56.20000   87.000000  2025-03-10 09:36:00
min      1.000000   19.00000   70.000000  2025-01-10 00:00:00
25%      2.000000   20.00000   80.000000  2025-02-15 00:00:00
50%      3.000000   21.00000   90.000000  2025-03-20 00:00:00
75%      4.000000   21.00000   90.000000  2025-04-01 00:00:00
max      5.000000  200.00000  105.000000  2025-05-01 00:00:00
std      1.581139   80.39092   13.038405                  NaN

In [101]:
print(df)

   student_id     name    age  marks  join_date
0           1    Alice   20.0   80.0 2025-01-10
1           2      Bob   21.0   90.0 2025-02-15
3           3  Charlie   21.0   70.0 2025-03-20
4           4    David  200.0  105.0 2025-04-01
5           5      Eve   19.0   90.0 2025-05-01