In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('dirty_dataset.csv')
df.head(10)

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
0,12369,Hasan D.,200.0,35149,2023-05-30,SALES,Man,America,Sylhet,118.4,0,Good value for money.,219.18,NaN,0
1,7361,Grace P.,NaN,77836,2017-02-27,Engineering,FEMALE,America,Chittagong,71kg,True,Product met all expectations.,329.26,NaN,0
2,3446,Eve D.,20.0,35404,2022-01-18,hr,male,BANGLADESH,Chitagong,98.7,False,Very satisfied with the quality.,438.6,NaN,0
3,18416,Diana E.,47.0,107375,2017-04-15,Marketing,Male,U.K.,Khulna,NaN,false,Delivery was fast and packaging great.,238.03,NaN,0
4,13677,Ira W.,64.0,55962,2021-11-02,SALES,F,United Kingdom,Dhaka,83.5,false,Would buy again without hesitation.,9.4,NaN,0
5,458,Frank Y.,38.0,88527,2022-08-16,Mrketing,male,UK,Sylhet,95.8,true,"Excellent product, highly recommend!",213.25,NaN,0
6,16484,John Q.,25.0,109079,2020-09-10,hr,Woman,us,Chitagong,125.2,False,Delivery was fast and packaging great.,19.35,NaN,0
7,12951,Charlie K.,22.0,$91118,2010-01-12,Finace,F,U.K.,Rajshahi,87.9,False,Delivery was fast and packaging great.,419.0,NaN,0
8,13108,Diana V.,43.0,88859,21/07/2016,Marketing,Male,United States,Khulna,73.8,True,good,430.17,NaN,0
9,14925,Alice C.,0.0,46627,2012-01-12,Sales,FEMALE,us,Khulna,110.7,False,Very satisfied with the quality.,429.27,NaN,0

In [6]:
df.tail(10)

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
20290,16444,Charlie I.,60.0,93596,2011-01-24,NaN,Woman,BANGLADESH,Chittagong,116.2,True,Good value for money.,79.97,NaN,0
20291,8369,John W.,24.0,95199,2024-03-28,hr,NaN,U.K.,Khulna,83kg,True,"Excellent product, highly recommend!",336.72,NaN,0
20292,16834,Grace F.,50.0,111758,2019-02-04,Engineering,Female,usa,Chittagong,69.4,False,Would buy again without hesitation.,472.76,NaN,0
20293,12274,Eve F.,50.0,32285,2016-03-21,Mrketing,Female,Bangladesh,NaN,129.4,False,Very satisfied with the quality.,234.92,NaN,0
20294,16440,Charlie W.,37.0,46333,01-27-2016,hr,MALE,U.S.A,Rajshahi,58kg,False,NaN,8.68,NaN,0
20295,19842,Frank N.,27.0,9999999,2010-06-21,engineering,Female,U.K.,Chittagong,93.7,False,Delivery was fast and packaging great.,$199.19,NaN,0
20296,1769,Frank N.,45.0,31616,2021-01-11,hr,F,U.K.,Khulna,NaN,False,Product met all expectations.,223.39,NaN,0
20297,9930,Hasan A.,30.0,70125,2013-07-07,Engineering,Woman,bd,Khulna,116.3,True,Would buy again without hesitation.,68.16,NaN,0
20298,3241,Frank D.,58.0,40120,2022-03-25,SALES,M,UK,Rajshahi,72.0,True,NaN,90.83,NaN,0
20299,13498,Alice X.,NaN,114722,2023-08-12,HR,Man,UK,Khulna,74.0,False,NaN,142.13,NaN,0

In [7]:
df.isnull().sum()

employee_id                0
name                       0
age                      621
salary                   610
join_date                810
department               857
gender                  1632
country                  608
city                     604
weight_kg                643
is_active                586
review                  1465
price                    446
weight_kg_duplicate    20300
target                     0
dtype: int64

In [8]:
df.isnull().mean()*100

employee_id              0.000000
name                     0.000000
age                      3.059113
salary                   3.004926
join_date                3.990148
department               4.221675
gender                   8.039409
country                  2.995074
city                     2.975369
weight_kg                3.167488
is_active                2.886700
review                   7.216749
price                    2.197044
weight_kg_duplicate    100.000000
target                   0.000000
dtype: float64

In [9]:
df1=df.copy()

In [11]:
df.duplicated().sum()

300

In [12]:
df.dtypes

employee_id              int64
name                    object
age                    float64
salary                  object
join_date               object
department              object
gender                  object
country                 object
city                    object
weight_kg               object
is_active               object
review                  object
price                   object
weight_kg_duplicate    float64
target                   int64
dtype: object

In [13]:
df.head(10)

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
0,12369,Hasan D.,200.0,35149,2023-05-30,SALES,Man,America,Sylhet,118.4,0,Good value for money.,219.18,NaN,0
1,7361,Grace P.,NaN,77836,2017-02-27,Engineering,FEMALE,America,Chittagong,71kg,True,Product met all expectations.,329.26,NaN,0
2,3446,Eve D.,20.0,35404,2022-01-18,hr,male,BANGLADESH,Chitagong,98.7,False,Very satisfied with the quality.,438.6,NaN,0
3,18416,Diana E.,47.0,107375,2017-04-15,Marketing,Male,U.K.,Khulna,NaN,false,Delivery was fast and packaging great.,238.03,NaN,0
4,13677,Ira W.,64.0,55962,2021-11-02,SALES,F,United Kingdom,Dhaka,83.5,false,Would buy again without hesitation.,9.4,NaN,0
5,458,Frank Y.,38.0,88527,2022-08-16,Mrketing,male,UK,Sylhet,95.8,true,"Excellent product, highly recommend!",213.25,NaN,0
6,16484,John Q.,25.0,109079,2020-09-10,hr,Woman,us,Chitagong,125.2,False,Delivery was fast and packaging great.,19.35,NaN,0
7,12951,Charlie K.,22.0,$91118,2010-01-12,Finace,F,U.K.,Rajshahi,87.9,False,Delivery was fast and packaging great.,419.0,NaN,0
8,13108,Diana V.,43.0,88859,21/07/2016,Marketing,Male,United States,Khulna,73.8,True,good,430.17,NaN,0
9,14925,Alice C.,0.0,46627,2012-01-12,Sales,FEMALE,us,Khulna,110.7,False,Very satisfied with the quality.,429.27,NaN,0